### ISSUE TITLE
Handler (android.os.Handler) {18aff90f} sending message to a Handler on a dead thread

### ISSUE THREAD

**Issue by JackyBower** [mywitness/Camara2-Video-Demo-fixed#1]
在返回或者重新拍摄的时候出现：`java.lang.IllegalStateException: Handler (android.os.Handler) {18aff90f} sending message to a Handler on a dead thread
at android.os.MessageQueue.enqueueMessage(MessageQueue.java:325)
at android.os.Handler.enqueueMessage(Handler.java:631)
at android.os.Handler.sendMessageAtFrontOfQueue(Handler.java:623)
at android.hardware.camera2.legacy.RequestThreadManager.quit(RequestThreadManager.java:941)
at android.hardware.camera2.legacy.LegacyCameraDevice.close(LegacyCameraDevice.java:444)
at android.hardware.camera2.legacy.LegacyCameraDevice.finalize(LegacyCameraDevice.java:468)
at java.lang.Daemons$FinalizerDaemon.doFinalize(Daemons.java:190)
at java.lang.Daemons$FinalizerDaemon.run(Daemons.java:173)
at java.lang.Thread.run(Thread.java:818)`

**Comment by mywitness** [comment]
@KitTak
sorry,my fault. The code what I have pushed is a wrong version. Then I'll push the right one.

**Comment by mywitness** [comment]
@KitTak
     hi, I've updated the code. the only difference between the correct one is app/build.gradle file.  I changed Android SDK version to 24. 
    you can now run to check if theres any bugs exits.
